#
# Makefile for the Linux ARC-specific parts of the memory manager.
#
# Copyright (C) 2003, ARC International
#

USE_STANDARD_AS_RULE := true

obj-y		+= extable.o iomap.o ioremap.o fault.o paging.o tlb.o tlbex.o

obj-y		+= init.o cache_arc700.o dma.o mmap.o

