#
# Makefile for the Linux ARC-specific parts of the memory manager.
#
# Copyright (C) 2003, ARC International
#

USE_STANDARD_AS_RULE := true

#O_TARGET	:= mm.o

# Object file lists.

obj-y		+= extable.o init.o iomap.o ioremap.o fault.o paging.o tlb.o tlbex.o cache_arc700.o dma.o

#include $(TOPDIR)/Rules.make
