#
# Copyright (C) 2012 Synopsys, Inc. (www.synopsys.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

obj-y += platform.o irq.o clock.o clkdev.o power_gate.o
obj-$(CONFIG_AM_INTC) += am_intc.o
