include include/asm-generic/Kbuild.asm

# 7-Oct-12: Jeremy Bennett <jeremy.bennett@embecosm.com>. Some of these
# headers, beyond those specified in the generic set are needed by user code.

unifdef-y += page.h
