#
# Copyright (C) 2012 Synopsys, Inc. (www.synopsys.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

obj-y += platform.o irq.o

obj-$(CONFIG_DW_GPIO) += dw_gpio.o
obj-$(CONFIG_DW_INTC) += dw_intc.o
