# Abilis Systems: TB100 platform Makefile
# Copyright (C) 2008-2012 Christian Ruppert <christian.ruppert@abilis.com>

KBUILD_CFLAGS	+= -Iarch/arc/plat-tb100/include

obj-y += tb100.o abilis_irqctl.o
obj-$(CONFIG_EARLY_PRINTK) += tb100_early_console.o
