#
# linux/arch/arc/drivers/Makefile
#
#

#O_TARGET	:= peripherals.o
#CFLAGS+= -mno-volatile-cache
obj-$(CONFIG_CARDREADER) +=  card_sysfs.o
obj-$(CONFIG_CARDREADER) +=  card_block.o
obj-$(CONFIG_CARDREADER) +=  cardreader.o
obj-$(CONFIG_CARDREADER) +=  card_io.o
obj-$(CONFIG_SD_MMC) += sd/

#include $(TOPDIR)/Rules.make

